autotest/autotest/urls.py
from django.contrib import admin
from django.urls import path
from apitest import views
from product import proviews
from bug import bugviews
from set import setviews
from apptest import appviews
from webtest import webviews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/',views.test),
    path('login/',views.login),
    path('home/',views.home),
    path('logout/',views.logout),
    #产品管理
    path('product_manage/',proviews.product_manage),

    path('apitest_manage/',views.apitest_manage),
    path('apistep_manage/',views.apistep_manage),

    path('apis_manage/',views.apis_manage),

    #bug管理
    path('bug_manage/',bugviews.bug_manage),

    #系统管理
    path('set_manage/',setviews.set_manage),

    #用户管理
    path('user/',setviews.set_user),

    #app测试用例管理
    path('appcase_manage/',appviews.appcase_manage),
    path('appcasestep_manage/',appviews.appcasestep_manage),

    #app测试用例管理
    path('webcase_manage/',webviews.webcase_manage),
    path('webcasestep_manage/',webviews.webcasestep_manage),

    #测试报告
    path('test_report/',views.test_report),
    path("apptest_report/",appviews.apptest_report),

    #优化
    path('left/',views.left),

    #搜索
    path('apisearch/',views.apisearch),
    path('setsearch/',setviews.setsearch),
    path('productsearch/',proviews.productsearch),
    path('apissearch/',views.apisearch),
    path('bugsearch/',bugviews.bugsearch),
    path('appsearch/',appviews.appsearch),
    path('appstepsearch/',appviews.appsetpsearch),
    path('websearch/',webviews.websearch),
    path('webstepsearch/',webviews.websetpsearch),
    path('usersearch/',setviews.usersearch),

]

autotest/apitest/models.py
from django.db import models
from product.models import Product
# Create your models here.

#流程接口表
class Apitest(models.Model):
    Product=models.ForeignKey('product.Product',on_delete=models.CASCADE)#关联的产品id
    apitestname=models.CharField('流程接口名',max_length=64)#流程接口测试场景
    apitestdesc=models.CharField('描述',max_length=64)#流程接口描述
    apitester=models.CharField('测试负责人',max_length=16)#测试负责人
    apitestresult=models.BooleanField('测试结果')#流程测试结果
    create_time=models.DateTimeField('创建时间',auto_now=True)#创建时间

    class Meta:
        verbose_name_plural='流程场景接口'


#接口表
class Apistep(models.Model):
    Apitest=models.ForeignKey(Apitest,on_delete=models.CASCADE)#关联接口ID
    apiname=models.CharField('接口标题',max_length=100)#接口名字
    apiurl=models.CharField('url地址',max_length=200)#接口地址
    apistep=models.CharField('接口测试步骤',max_length=100,null=True)#测试步骤
    apiparamvalue = models. CharField('请求参数和值',max_length=800) #请求参数和值
    REQUEST_METHOD=(('get','get'),('post','post'))
    apimethod=models.CharField(verbose_name='请求方法',choices=REQUEST_METHOD,default='get',max_length=200,null=True) #请求方法
    apiresult=models.CharField('预期结果',max_length=200) #预期结果
    apiresponse=models.CharField('响应结果',max_length=5000,null=True)#响应结果
    apistatus=models.BooleanField('是否通过')#测试结果
    create_time=models.DateTimeField('创建时间',auto_now=True)

#单一接口表
class Apis(models.Model):
    product = models.ForeignKey('product.Product', on_delete=models.CASCADE)  # 关联的产品id
    apiname = models.CharField('接口标题', max_length=100)  # 接口名字
    apiurl = models.CharField('url地址', max_length=200)  # 接口地址
    apiparamvalue = models.CharField('请求参数和值', max_length=800)  # 请求参数和值
    REQUEST_METHOD = (('0', 'get'), ('1', 'post'))
    apimethod = models.CharField(verbose_name='请求方法', choices=REQUEST_METHOD, default='0', max_length=200)  # 请求方法
    apiresult = models.CharField('预期结果', max_length=200)  # 预期结果
    apistatus = models.BooleanField('是否通过')  # 测试结果
    create_time = models.DateTimeField('创建时间', auto_now=True) #创建时间
    producter=models.CharField('产品负责人',max_length=200,null=True)#产品负责人

    class Meta:
        verbose_name_plural="单一场景接口"

autotest/apitest/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.contrib.auth import authenticate,login
from .models import Apistep,Apitest,Apis
import pymysql
import HTMLTestReportCN
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
def test(request):
    return HttpResponse("hello test")

#登陆功能
def login(request):
    if request.POST:
        #username=password=''
        username=request.POST.get("username")
        password=request.POST.get("password")
        user=auth.authenticate(username=username,password=password)
        if user is not None and user.is_active:
            auth.login(request,user)
            request.session['user']=username
            response=HttpResponseRedirect('/home/')
            return response
        else:
            return render(request,'login.html',{'error':' 用户名或密码错误！'})
    return render(request,'login.html')

def home(request):
    return render(request,"home.html")
# 退出，
def logout(request):
    auth.logout(request)
    return render(request,'login.html')

#流程接口管理+分页功能
def apitest_manage(request):
    apitest_list=Apitest.objects.all()
    username=request.session.get("user")
    paginator=Paginator(apitest_list,10)
    page=request.GET.get('page',1)
    currentPage=int(page)
    try:
        apitest_list=paginator.page(page)
    except PageNotAnInteger:
        apitest_list=paginator.page(paginator.num_pages)
    apitest_count = Apitest.objects.all().count()
    return render(request,"apitest_manage.html",{"user":username,"apitests":apitest_list,"apitestcounts":apitest_count})

#接口步骤管理
#@login_required
def apistep_manage(request):
    username=request.session.get("user")
    apistep_list=Apistep.objects.all()
    paginator = Paginator(apistep_list, 10)
    page = request.GET.get('page', 1)
    currentPage = int(page)
    try:
        apistep_list = paginator.page(page)
    except PageNotAnInteger:
        apistep_list = paginator.page(paginator.num_pages)
    return render(request,"apistep_manage.html",{"user":username,"apisteps":apistep_list})

#单一接口管理
def apis_manage(request):
    username=request.session.get('user')
    apis_list=Apis.objects.all()
    paginator = Paginator(apis_list, 10)
    page = request.GET.get('page', 1)
    currentPage = int(page)
    try:
        apis_list = paginator.page(page)
    except PageNotAnInteger:
        apis_list = paginator.page(paginator.num_pages)

    apis_count = Apis.objects.all().count()
    return render(request,"apis_manage.html",{'user':username,'apiss':apis_list,"apiscounts":apis_count})

#测试报告
def test_report(request):
    username = request.session.get('user')
    apis_list = Apis.objects.all()
    apis_count=Apis.objects.all().count()#统计接口数量
    db=pymysql.connect(user='root',db='autotest',passwd='123456',host='127.0.0.1')
    cursor=db.cursor()
    sql1='select count(id) from apitest_apis where apitest_apis.apistatus=1'
    aa=cursor.execute(sql1)
    apis_pass_count=[row[0] for row in cursor.fetchmany(aa)][0]

    sql2='select count(id) from apitest_apis where apitest_apis.apistatus=0'
    bb=cursor.execute(sql2)

    apis_fail_count=[row[0] for row in cursor.fetchmany(bb)][0]
    db.close()

    return render(request,"report.html",{'user':username,"apiss":apis_list,"apiscounts":apis_count,
                                         "apis_pass_counts":apis_pass_count,"apis_fail_counts":apis_fail_count})

def left(request):
    return render(request,"left.html")

#搜索功能
def apisearch(request):
    username=request.session.get("user")
    search_apitestname=request.GET.get("apitestname")
    apitest_list=Apitest.objects.filter(apitestname__icontains=search_apitestname)
    return render(request,'apitest_manage.html',{"user":username,"apitests":apitest_list})



#搜索
def apissearch(request):
    username=request.session.get("user")
    search_apiname=request.GET.get("apiname")
    apis_list=Apis.objects.filter(apiname_icontains=search_apiname)
    return render(request,'apis_manage.html',{"user":username,"apiss":apis_list})

autotest/apitest/templates/apis_manage.html
{% load bootstrap4 %}
{% bootstrap_javascript %}
{% bootstrap_css %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>产品自动化测试管理平台</title>

    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/acore.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
    <meta name="viewport" charset="UTF-8" content="user-scalable=no,width=device-width,initial-scale=1.0,maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
    <meta name="robots" content="NONE,NOARCHIVE" />
</head>
<body role="document">
    <nav class="navbar navbar-inverse navbar-fixed-top">

        <div class="container">

            <div class="navbar-header">
                <a class="navbar-brand" href="#">产品自动化测试管理平台</a>
            </div>

            <div id="navbar" class="collapse navbar-collapse">

            <ul class="nav navbar-nav">
                <li class="active"><a style="color: white" href="/apis_manage"></a>单一接口测试用例</li>
            </ul>



            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">{{ user }}</a></li>
                <li><a href="/logout/">退出</a></li>
            </ul>
        </div>
        </div>
    </nav>

{#单一接口测试用例#}
<div class="row" style="padding-top: 20px">

{#    增加api流程测试用例#}
    <div style="float: right;width: 73%">
        <select name="Apis" id="id_Apis">
            <option value="" selected>
                ----api单一接口测试用例----
            </option>
        </select>
    </div>

    <a class="related-widget-wrapper-link change-related" id="change_id_Apis" data-href-template="/admin/apitest/apis/__fk__/change/?
    _to_field=id&amp;_popup=1" title="更改选中的测试地址">
        <img src="/static/admin/img/icon-changelink.svg" alt="修改" />
    </a>

    <a class="related-widget-wrapper-link add-another" id="add_id_Apis" href="admin/apitest/apis/add/?_to_field=id&amp;__popup=1"
    title="增加一个测试用例">
        <img src="/static/admin/img/icon-changelink.svg" alt="增加" />增加
    </a>


  <div class="page-header" style="padding-top: 10px">
           <form class="navbar-form" method="get" action="/apissearch/">
                <input type="search" name="apiname" placeholder="名称" required>
                <button type="submit">搜索</button>

            </form>
        </div>

    <div class="col-md-11">
        <table class="table table-striped">
            <thead>

            <tr>
                <th>ID</th>
                <th>产品</th>
                <th>单一接口测试用例名称</th>
                <th>URL地址</th>
                <th>参数=值</th>
                <th>方法</th>
                <th>预期结果</th>
                <th>测试结果</th>
                <th>测试负责人</th>
                <th>时间</th>

                <th>编辑</th>
                <th>删除</th>


            </tr>
            </thead>

            <tbody>
            {% for apis in apiss %}
                <tr>
                <td>{{ apis.id }}</td>
                <td>{{ apis.Product.productname }}</td>
                <td>{{ apis.apiname }}</td>
                <td>{{ apis.apiurl }}</td>
                <td>{{ apis.apiparamvalue }}</td>
                <td>{{ apis.apimethod }}</td>
                <td>{{ apis.apiresult}}</td>
                <td>{{ apis.apistatus}}</td>
{#                <td>{{ apis.producter}}</td>#}
                <td>{{ apis.create_time}}</td>
{#编辑#}
                <td>
                    <a style="color: blue" class="related-widget-wrapper-link add-related" id="add_id_Apis"
                    href="../admin/apitest/apis/{{ apis.id }}/change/?_to_field=id&_popup=1">
                        <img src="/static/admin/img/icon-changelink.svg">
                    </a>
                </td>

                 <td>
                    <a style="color: lightblue" class="related-widget-wrapper-link add-related" id="add_id_Apis"
                    href="../admin/apitest/apis/{{ apis.id }}/delete/?_to_field=id&_popup=1">
                        <img src="/static/admin/img/icon-changelink.svg">
                    </a>
                </td>



                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{#翻页功能#}
<span style="position: absolute;right: 100px;bottom: 30px"></span>

{#统计#}
<div style="position: absolute;right: 100px;bottom:30px">
    <tr><th>共</th><td>{{ apiscounts }}条记录</td></tr>
</div>

<div class="container">
    <ul class="pagination" id="pager">

        {% if apiss.has_previous %}
            <li class="previous">
                <a href="/apis_manage/?page={{ apiss.previous_page_number }}">
                     上一页
                </a>
            </li>

            {% else %}
            <li class="previous disabled">
                <a href="#">
                    上一页
                </a>
            </li>
        {% endif %}

        {% for num in apiss.paginator.page_range %}
            {% if num == currentPage %}
            <li class="item active">
                <a href="/apis_manage/?page={{ num }}">
                    {{ num }}
                </a>
            </li>

                {% else %}
                <li class="item">
                    <a href="/apis_manage/?page={{ num }}">
                        {{ num }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}

        {% if apiss.has_next %}
            <li class="next">
                <a href="/apis_manage/?page={{ apiss.next_page_number }}">
                    下一页
                </a>
            </li>

            {% else %}
            <li class="next disabled">
                <a href="#">
                    下一页
                </a>
            </li>
        {% endif %}
    </ul>

</div>

</body>
</html>

autotest/apitest/templates/apistep_manage.html
{% load bootstrap4 %}
{% bootstrap_javascript %}
{% bootstrap_css %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自动化测试平台</title>
</head>

<body role="document">

    <nav class="navbar navbar-inverse navbar-fixed-top">

        <div class="container">

            <div class="navbar-header">
                <a class="navbar-brand" href="#">自动化测试平台</a>
            </div>

            <div id="navbar" class="collapse navbar-collapse">

            <ul class="nav navbar-nav">
                 <li class="active"><a style="color: white" href="/apistep_manage">流程接口测试步骤</a></li>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <li class="active"><a href="apistep_manage/"> 流程接口测试步骤</a></li>
            </ul>



            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">{{ user }}</a></li>
                <li><a href="/logout/">退出</a></li>
            </ul>
        </div>
        </div>

    </nav>

{#流程接口测试步骤#}
<div class="row" style="padding-top: 70px">
    <div class="col-md-11">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>接口名称</th>
                <th>接口URL</th>
                <th>参数=值</th>
                <th>方法</th>
                <th>预期结果</th>
                <th>测试结果</th>
                <th>时间</th>
                <th>业务流程名</th>
            </tr>
            </thead>

            <tbody>
            {% for apistep in apisteps %}
                <tr>
                <td>{{ apistep.id}}</td>
                <td>{{ apistep.apiname }}</td>
                <td>{{ apistep.apiurl }}</td>
                <td>{{ apistep.apiparamvalue }}</td>
                <td>{{ apistep.apimethod }}</td>
                <td>{{ apistep.apiresult }}</td>
                <td>{{ apistep.apistatus }}</td>
{#                <td>{% if apistep.apistatus == 1 %}#}
{#                <a style="color: green">{{ apistep.apistatus }}</a>#}
{#                {% else %}#}
{#                <a style="color: red">{{ apistep.apistatus }}</a>#}
{#                {% endif %}#}
{#                </td>#}

                <td>{{ apistep.create_time }}</td>
                </tr>
            {% endfor %}
            </tbody>

        </table>
    </div>
</div>



{#翻页功能#}
<span style="position: absolute;right: 100px;bottom: 30px"></span>
<div class="container">
    <ul class="pagination" id="pager">

        {% if apisteps.has_previous %}
            <li class="previous">
                <a href="/apistep_manage/?page={{ apisteps.previous_page_number }}">
                     上一页
                </a>
            </li>

            {% else %}
            <li class="previous disabled">
                <a href="#">
                    上一页
                </a>
            </li>
        {% endif %}

        {% for num in apisteps.paginator.page_range %}
            {% if num == currentPage %}
            <li class="item active">
                <a href="/apistep_manage/?page={{ num }}">
                    {{ num }}
                </a>
            </li>

                {% else %}
                <li class="item">
                    <a href="/apistep_manage/?page={{ num }}">
                        {{ num }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}

        {% if apisteps.has_next %}
            <li class="next">
                <a href="/apistep_manage/?page={{ apisteps.next_page_number }}">
                    下一页
                </a>
            </li>

            {% else %}
            <li class="next disabled">
                <a href="#">
                    下一页
                </a>
            </li>
        {% endif %}
    </ul>

</div>

</body>
</html>

autotest/apitest/templates/apitest_manage.html
{% load bootstrap4 %}
{% bootstrap_javascript %}
{% bootstrap_css %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>自动化测试平台</title>

    <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/acore.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
    <meta name="viewport" charset="UTF-8" content="user-scalable=no,width=device-width,initial-scale=1.0,maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
    <meta name="robots" content="NONE,NOARCHIVE" />
</head>

<body role="document">
<!--导航栏-->
    <nav class="navbar navbar-expand-sm bg-dark nav-dark navbar-fixed-top">
    </nav>

{#流程接口列表#}
<div class="row" style="padding-top: 30px">

{#    增加api流程测试用例#}
    <div style="float: right;width: 73%">
        <select name="Apitest" id="id_Apitest">
            <option value="" selected>
                ----api流程测试用例----
            </option>
        </select>
    </div>

    <a class="related-widget-wrapper-link change-related" id="change_id_Apitest" data-href-template="/admin/apitest/apitest/__fk__/change/?
    _to_field=id&amp;_popup=1" title="更改选中的测试地址">
        <img src="/static/admin/img/icon-changelink.svg" alt="修改" />
    </a>

    <a class="related-widget-wrapper-link add-another" id="add_id_Apitest" href="admin/apitest/apitest/add/?_to_field=id&amp;__popup=1"
    title="增加一个测试用例">
        <img src="/static/admin/img/icon-changelink.svg" alt="增加" />增加
    </a>

{##搜索功能#}
        <div class="page-header" style="padding-top: 10px">
            <form class="navbar-form" method="get" action="/apisearch/">
                <input type="search" name="apitestname" placeholder="名称" required>
                <button type="submit">搜索</button>

            </form>
        </div>

    <div class="col-md-11">
        <table class="table table-striped">
            <thead>

            <tr>
                <th>ID</th>
                <th>业务接口流程名称</th>
                <th>测试负责人</th>
                <th>结果</th>
                <th>接口列表</th>
                <th>编辑</th>

            </tr>
            </thead>

            <tbody>
            {% for apitest in apitests %}
                <tr>
                <td>{{ apitest.id }}</td>
                <td>{{ apitest.apitestname }}</td>
                <td>{{ apitest.apitester }}</td>
                <td>{{ apitest.apitestresult }}</td>
                    <td>
    <a style="color: blue" class="related-widget-wrapper-link add-another" id="add_id_Apitest"
    href="../admin/apitest/apitest/{{ apitest.id }}/change/?_to_field=id&_popup=1">
        <img src="/static/admin/img/icon-changelink.svg">
    </a>
</td>


{#                <td>{% if  apitest.apitestresult == 1 %}#}
{#                    <a style="color: green">{{ apitest.apitestresult }}</a>#}
{#                    {% else %}#}
{#                     <a style="color: red">{{ apitest.apitestresult }}</a>#}
{#                    {% endif %}#}
{#                    </td>#}
{##}
{#                <td>{{ apitest.Apistep.apiteststep }}</td>#}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>



{#翻页功能#}
<span style="position: absolute;right: 100px;bottom: 30px"></span>

#统计
<div style="position: absolute;right: 100px;bottom:30px">
    <tr><th>共</th><td>{{ apitestcounts }}条记录</td></tr>
</div>

<div class="container">
    <ul class="pagination" id="pager">

        {% if apitests.has_previous %}
            <li class="previous">
                <a href="/apitest_manage/?page={{ apitests.previous_page_number }}">
                     上一页
                </a>
            </li>

            {% else %}
            <li class="previous disabled">
                <a href="#">
                    上一页
                </a>
            </li>
        {% endif %}

        {% for num in apitests.paginator.page_range %}
            {% if num == currentPage %}
            <li class="item active">
                <a href="/apitest_manage/?page={{ num }}">
                    {{ num }}
                </a>
            </li>

                {% else %}
                <li class="item">
                    <a href="/apitest_manage/?page={{ num }}">
                        {{ num }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}

        {% if apitests.has_next %}
            <li class="next">
                <a href="/apitest_manage/?page={{ apitests.next_page_number }}">
                    下一页
                </a>
            </li>

            {% else %}
            <li class="next disabled">
                <a href="#">
                    下一页
                </a>
            </li>
        {% endif %}
    </ul>

</div>

</body>
</html>

autotest/apitest/templates/home.html
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8" http-equiv="Content-Type" content="text/html" />
<head>

    <title>自动化测试平台</title>
</head>

{#<frameset id="framel" rows="*" cols="265,*" framespacing="0" frameborder="yes" border="0"></frameset>#}
{#<frame src="#" name="leftFrame" scrolling="auto" noresize="">#}
{#<frame src="#" name="mianFrame" scrolling="NO" noresize="">#}


    <body>
    <ul class="nav navbar-nav navbar-right">
        <li>欢迎您:<a href="#">{{ user }}</a></li>
        <li><a href="/logout">退出</a></li>
    </ul>
</body>
</html>

autotest/apitest/templates/left.html
{% load bootstrap4 %}
{% bootstrap_javascript %}
{% bootstrap_css %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>test</title>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark navbar-fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/apitest_manage" target="mainFrame">
            接口自动化测试平台开发
        </a>
    </div>
</nav>
<table border="0">
    <tr><td>&nbsp</td></tr>
    <tr><td>&nbsp</td></tr>
    <tr><td>&nbsp;</td></tr>
    <tr><td>&nbsp;</td></tr>

    <tr>
        <td><a href="/apitest_manage/" target="mianFrame">&nbsp;&nbsp;项目管理</a></td>
    </tr>

    <tr><td>&nbsp;</td></tr>
    <tr>
        <td>
            <a>----------------------------------------------------------------------------</a>
        </td>
    </tr>
    <tr><td>&nbsp;</td></tr>

    <tr>
        <td>
            <a href="/apitest_manage" target="mainFrame">&nbsp;&nbsp;接口用例管理</a>
        </td>
    </tr>
    <tr><td>&nbsp;</td></tr>

       <tr> <td><a href="/apitest_manage/" target="mianFrame">&nbsp;&nbsp;流程接口测试用例</a></td></tr>
        <tr><td>&nbsp;</td></tr>

    <tr>
        <td><a href="/appcase_manage/" target="mianFrame">&nbsp;&nbsp;流程接口测试用例步骤</a></td>
    </tr>
    <tr><td>&nbsp;</td></tr>

    <tr>
        <td>
            <a>----------------------------------------------------------------------------</a>
        </td>
    </tr>
    <tr><td>&nbsp;</td></tr>

    <tr>
        <td>
            <a href="/appcase_manage" target="mainFrame">&nbsp;&nbsp;app用例管理</a>
        </td>
    </tr>
    <tr><td>&nbsp;</td></tr>
    <tr>
        <td>
            <a href="/appcase_manage" target="mainFrame">&nbsp;&nbsp;app测试用例</a>
        </td>
    </tr>
    <tr><td>&nbsp;</td></tr>


    <tr>
        <td>
            <a>----------------------------------------------------------------------------</a>
        </td>
    </tr>
    <tr><td>&nbsp;</td></tr>

    <tr>
        <td>
            <a href="/webcase_manage" target="mainFrame">&nbsp;&nbsp;web用例管理</a>
        </td>
    </tr>
    <tr><td>&nbsp;</td></tr>
     <tr>
        <td>
            <a href="/webcase_manage" target="mainFrame">&nbsp;&nbsp;web测试用例</a>
        </td>
    </tr>
    <tr><td>&nbsp;</td></tr>

    <tr>
        <td>
            <a>----------------------------------------------------------------------------</a>
        </td>
    </tr>
    <tr><td>&nbsp;</td></tr>

    <tr>
        <td><a href="http://127.0.0.1:8000/admin/apitest/apitest/add/" target="mianFrame">&nbsp;&nbsp;任务管理</a></td>
    </tr>
    <tr><td>&nbsp;</td></tr>

    <tr>
        <td>
            <a>----------------------------------------------------------------------------</a>
        </td>
    </tr>
    <tr><td>&nbsp;</td></tr>

    <tr>
        <td><a href="http://127.0.0.1:8000/admin/apitest/apitest/add/" target="mianFrame">&nbsp;&nbsp;测试报告</a></td>
    </tr>

</table>

</body>
</html>