autotest/autotest/urls.py
from django.contrib import admin
from django.urls import path
from apitest import views
from product import proviews
from bug import bugviews
from set import setviews
from apptest import appviews
from webtest import webviews


urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/',views.test),
    path('login/',views.login),
    path('home/',views.home),
    path('logout/',views.logout),
    #产品管理
    path('product_manage/',proviews.product_manage),

    path('apitest_manage/',views.apitest_manage),
    path('apistep_manage/',views.apistep_manage),

    path('apis_manage/',views.apis_manage),

    #bug管理
    path('bug_manage/',bugviews.bug_manage),

    #系统管理
    path('set_manage/',setviews.set_manage),

    #用户管理
    path('user/',setviews.set_user),

    #app测试用例管理
    path('appcase_manage/',appviews.appcase_manage),
    path('appcasestep_manage/',appviews.appcasestep_manage),

    #app测试用例管理
    path('webcase_manage/',webviews.webcase_manage),
    path('webcasestep_manage/',webviews.webcasestep_manage),

    #测试报告
    path('test_report/',views.test_report),
    path("apptest_report/",appviews.apptest_report),

    #优化
    path('left/',views.left),

    #搜索
    path('apisearch/',views.apisearch),
    path('setsearch/',setviews.setsearch),
    path('productsearch/',proviews.productsearch),
    path('apissearch/',views.apisearch),
    path('bugsearch/',bugviews.bugsearch),
    path('appsearch/',appviews.appsearch),
    path('appstepsearch/',appviews.appsetpsearch),
    path('websearch/',webviews.websearch),
    path('webstepsearch/',webviews.websetpsearch),
    path('usersearch/',setviews.usersearch),

]

autotest/bug/models.py
from django.db import models
from product.models import Product

# Create your models here.
class Bug(models.Model):
    Product=models.ForeignKey('product.Product',on_delete=models.CASCADE,null=True)#关联产品ID
    bugname=models.CharField('bug名称',max_length=64) #bug名称
    bugdetail=models.CharField('bug详情',max_length=200)#bug详情
    BUG_STATUS=(('激活','激活'),('已解决','已解决'),('已关闭','已关闭'))
    bugstatus=models.CharField(verbose_name='解决状态',choices=BUG_STATUS,default='激活',max_length=200,null=True)#解决状态
    BUG_LEVEL=(('1','1'),('2','2'),('3','3'))
    buglevel=models.CharField(verbose_name='严重程度',choices=BUG_LEVEL,default='3',max_length=200,null=True)#bug严重程度
    bugcreater=models.CharField('创建人',max_length=200)#创建人
    bugassign=models.CharField('分配给',max_length=200)#分配给
    create_time=models.DateTimeField('创建时间',auto_now=True)#更新时间
    class Meta:
        verbose_name_plural='bug管理'

autotest/product/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    productname=models.CharField('产品名称',max_length=64,null=False)
    productdescription=models.CharField('产品描述',max_length=200,null=False)
    producter=models.CharField('测试人员',max_length=20,null=False)
    create_time=models.DateTimeField('创建时间',auto_now=True)

    class Meta:
        verbose_name_plural="产品管理"

autotest/product/templates/product_manage.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>产品自动化测试平台</title>

     <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />
    <script type="text/javascript" src="/admin/jsi18n/"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
    <script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/static/admin/js/acore.js"></script>
    <script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/static/admin/js/urlify.js"></script>
    <script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
    <script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
    <meta name="viewport" charset="UTF-8" content="user-scalable=no,width=device-width,initial-scale=1.0,maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css" />
    <meta name="robots" content="NONE,NOARCHIVE" />
</head>

<body role="document">
<nav class="navbar navbar-expand-sm bg-dark navbar-dark navbar-fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#">&nbsp;</a>
        <ul class="nav justify-content-end">
        <li class="navbar-link"><a style="color: white" href="#">{{ user }}</a></li>
        <li class="navbar-link"><a style="color: white" href="/logout/">&nbsp;&nbsp;退出</a></li>
            </ul>
    </div>
</nav>

<div class="row" style="padding-top: 1px">

{#    增加app流程测试用例#}
    <div style="float: right;width: 73%">
        <select name="Product" id="id_Product">
            <option value="" selected>
                ----app测试用例----
            </option>
        </select>
    </div>

    <a class="related-widget-wrapper-link change-related" id="change_id_Product" data-href-template="/admin/product/product/__fk__/change/?
    _to_field=id&amp;_popup=1" title="更改选中的测试地址">
        <img src="/static/admin/img/icon-changelink.svg" alt="修改" />
    </a>

    <a class="related-widget-wrapper-link add-another" id="add_id_Product" href="admin/product/product/add/?_to_field=id&amp;__popup=1"
    title="增加一个测试用例">
        <img src="/static/admin/img/icon-changelink.svg" alt="增加" />增加
    </a>


  <div class="page-header" style="padding-top: 10px">
           <form class="navbar-form" method="get" action="/productsearch/">
                <input type="search" name="productname" placeholder="名称" required>
                <button type="submit">搜索</button>

            </form>
        </div>

    <div class="col-md-11">
        <table class="table table-striped">
            <thead>
                <tr><td>&nbsp;</td></tr>
            <tr>
                <th>ID</th>
                <th>产品名称</th>
                <th>产品描述</th>
                <th>测试人员</th>
                <th>创建时间</th>
                <th>编辑</th>
                <th>删除</th>
            </tr>
            </thead>

            <tbody>
                {% for product in products %}
                    <tr>
                    <td>{{ product.id }}</td>
                    <td>{{ product.productname }}</td>
                    <td>{{ product.productdescription }}</td>
                    <td>{{ product.producter }}</td>
                    <td>{{ product.create_time }}</td>
                    <td>
                        <a style="color: blue" class="related-widget-wrapper-link add-related" id="add_id_Product"
                        href="../admin/product/product/{{ product.id }}/change/?_to_field=id&_popup=1">
                        <img src="/static/admin/img/icon-changelink.svg">
                        </a>
                    </td>
                        <td>
                        <a style="color: lightblue" class="related-widget-wrapper-link add-another" id="add_id_Product"
                        href="../admin/product/product/{{ product.id }}/delete/?_to_field=id&_popup=1">
                        <img src="/static/admin/img/icon-changelink.svg">
                        </a>
                    </td>

                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{#翻页功能#}
<span style="position: absolute;right: 100px;bottom: 30px"></span>

#统计
<div style="position: absolute;right: 100px;bottom:30px">
    <tr><th>共</th><td>{{ productcounts }}条记录</td></tr>
</div>

<div class="container">
    <ul class="pagination" id="pager">

        {% if products.has_previous %}
            <li class="previous">
                <a href="/product_manage/?page={{ products.previous_page_number }}">
                     上一页
                </a>
            </li>

            {% else %}
            <li class="previous disabled">
                <a href="#">
                    上一页
                </a>
            </li>
        {% endif %}

        {% for num in products.paginator.page_range %}
            {% if num == currentPage %}
            <li class="item active">
                <a href="/products_manage/?page={{ num }}">
                    {{ num }}
                </a>
            </li>

                {% else %}
                <li class="item">
                    <a href="/product_manage/?page={{ num }}">
                        {{ num }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}

        {% if products.has_next %}
            <li class="next">
                <a href="/product_manage/?page={{ products.next_page_number }}">
                    下一页
                </a>
            </li>

            {% else %}
            <li class="next disabled">
                <a href="#">
                    下一页
                </a>
            </li>
        {% endif %}
    </ul>

</div>

</body>
</html>